#!/usr/bin/bash

# Get sensors
sensors=$(find /sys/devices -type f -name 'temp*_input' | sed -e "s/.*thinkpad_hwmon.*temp2_input//g" |xargs -I {} echo "hwmon {}")

# Generate and overwrite /etc/thinkfan.conf
cat > /etc/thinkfan.conf << EOF
######################################################################
# WARNING: Do not modify. Generated by ${0}.
######################################################################
#
# IBM/Lenovo Thinkpads (thinkpad_acpi, /proc/acpi/ibm)
# ====================================================
#
# IMPORTANT:
#
# To keep your HD from overheating, you have to specify a correction value for
# the sensor that has the HD's temperature. You need to do this because
# thinkfan uses only the highest temperature it can find in the system, and
# that'll most likely never be your HD, as most HDs are already out of spec
# when they reach 55 °C.
# Correction values are applied from left to right in the same order as the
# temperatures are read from the file.
#
# For example:
# tp_thermal /proc/acpi/ibm/thermal (0, 0, 10)
# will add a fixed value of 10 °C the 3rd value read from that file. Check out
# http://www.thinkwiki.org/wiki/Thermal_Sensors to find out how much you may
# want to add to certain temperatures.

# use legacy fan control
tp_fan /proc/acpi/ibm/fan
# disable using sysfs pwm
# pwm_fan /sys/devices/platform/thinkpad_hwmon/pwm1

# sensors
${sensors}


#  Syntax:
#  (LEVEL, LOW, HIGH)
#  LEVEL is the fan level to use (0-7 with thinkpad_acpi)
#  LOW is the temperature at which to step down to the previous level
#  HIGH is the temperature at which to step up to the next level
#  All numbers are integers.
#
(0,0,45)
(1,34,48)
(2,36,51)
(3,39,53)
(4,46,55)
(5,49,56)
(6,50,58)
(7,53,32767)
EOF

systemctl restart thinkfan
